/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.dc.entity.lang.EntityDslRuntimeModule;
import de.dc.entity.lang.EntityDslStandaloneSetup;
import de.dc.entity.lang.ide.EntityDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EntityDslIdeSetup extends EntityDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    EntityDslRuntimeModule _entityDslRuntimeModule = new EntityDslRuntimeModule();
    EntityDslIdeModule _entityDslIdeModule = new EntityDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_entityDslRuntimeModule, _entityDslIdeModule));
  }
}
