/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.ide;

import de.dc.entity.lang.ide.AbstractEntityDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntityDslIdeModule extends AbstractEntityDslIdeModule {
}
