/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.ui.contentassist;

import de.dc.entity.lang.ui.contentassist.AbstractEntityDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EntityDslProposalProvider extends AbstractEntityDslProposalProvider {
}
