/*
 * generated by Xtext 2.19.0
 */
package de.dc.entity.lang.serializer;

import com.google.inject.Inject;
import de.dc.entity.lang.services.EntityDslGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class EntityDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EntityDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_FXControl_CommaKeyword_2_2_q;
	protected AbstractElementAlias match_FXControl_CommaKeyword_3_2_q;
	protected AbstractElementAlias match_FXControl_CommaKeyword_4_2_q;
	protected AbstractElementAlias match_FXControl_CommaKeyword_5_2_q;
	protected AbstractElementAlias match_Field_CommaKeyword_3_2_q;
	protected AbstractElementAlias match_Field_CommaKeyword_4_2_q;
	protected AbstractElementAlias match_Field_CommaKeyword_5_2_q;
	protected AbstractElementAlias match_Field_CommaKeyword_6_2_q;
	protected AbstractElementAlias match_Field_CommaKeyword_7_2_q;
	protected AbstractElementAlias match_Metro_CommaKeyword_8_2_0_q;
	protected AbstractElementAlias match_PageContainer_CommaKeyword_3_1_0_q;
	protected AbstractElementAlias match_PageContainer_CommaKeyword_4_1_0_q;
	protected AbstractElementAlias match_Repository_CommaKeyword_3_2_q;
	protected AbstractElementAlias match_Repository_CommaKeyword_4_2_q;
	protected AbstractElementAlias match_SQLStatement_CommaKeyword_3_2_q;
	protected AbstractElementAlias match_SQLStatement_CommaKeyword_4_2_q;
	protected AbstractElementAlias match_SpringMetro_CommaKeyword_7_2_0_q;
	protected AbstractElementAlias match_XBlockExpression_SemicolonKeyword_2_1_q;
	protected AbstractElementAlias match_XExpressionInClosure_SemicolonKeyword_1_1_q;
	protected AbstractElementAlias match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q;
	protected AbstractElementAlias match_XImportDeclaration_SemicolonKeyword_2_q;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_a;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EntityDslGrammarAccess) access;
		match_FXControl_CommaKeyword_2_2_q = new TokenAlias(false, true, grammarAccess.getFXControlAccess().getCommaKeyword_2_2());
		match_FXControl_CommaKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getFXControlAccess().getCommaKeyword_3_2());
		match_FXControl_CommaKeyword_4_2_q = new TokenAlias(false, true, grammarAccess.getFXControlAccess().getCommaKeyword_4_2());
		match_FXControl_CommaKeyword_5_2_q = new TokenAlias(false, true, grammarAccess.getFXControlAccess().getCommaKeyword_5_2());
		match_Field_CommaKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getFieldAccess().getCommaKeyword_3_2());
		match_Field_CommaKeyword_4_2_q = new TokenAlias(false, true, grammarAccess.getFieldAccess().getCommaKeyword_4_2());
		match_Field_CommaKeyword_5_2_q = new TokenAlias(false, true, grammarAccess.getFieldAccess().getCommaKeyword_5_2());
		match_Field_CommaKeyword_6_2_q = new TokenAlias(false, true, grammarAccess.getFieldAccess().getCommaKeyword_6_2());
		match_Field_CommaKeyword_7_2_q = new TokenAlias(false, true, grammarAccess.getFieldAccess().getCommaKeyword_7_2());
		match_Metro_CommaKeyword_8_2_0_q = new TokenAlias(false, true, grammarAccess.getMetroAccess().getCommaKeyword_8_2_0());
		match_PageContainer_CommaKeyword_3_1_0_q = new TokenAlias(false, true, grammarAccess.getPageContainerAccess().getCommaKeyword_3_1_0());
		match_PageContainer_CommaKeyword_4_1_0_q = new TokenAlias(false, true, grammarAccess.getPageContainerAccess().getCommaKeyword_4_1_0());
		match_Repository_CommaKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getRepositoryAccess().getCommaKeyword_3_2());
		match_Repository_CommaKeyword_4_2_q = new TokenAlias(false, true, grammarAccess.getRepositoryAccess().getCommaKeyword_4_2());
		match_SQLStatement_CommaKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getSQLStatementAccess().getCommaKeyword_3_2());
		match_SQLStatement_CommaKeyword_4_2_q = new TokenAlias(false, true, grammarAccess.getSQLStatementAccess().getCommaKeyword_4_2());
		match_SpringMetro_CommaKeyword_7_2_0_q = new TokenAlias(false, true, grammarAccess.getSpringMetroAccess().getCommaKeyword_7_2_0());
		match_XBlockExpression_SemicolonKeyword_2_1_q = new TokenAlias(false, true, grammarAccess.getXBlockExpressionAccess().getSemicolonKeyword_2_1());
		match_XExpressionInClosure_SemicolonKeyword_1_1_q = new TokenAlias(false, true, grammarAccess.getXExpressionInClosureAccess().getSemicolonKeyword_1_1());
		match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getLeftParenthesisKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getRightParenthesisKeyword_0_2()));
		match_XImportDeclaration_SemicolonKeyword_2_q = new TokenAlias(false, true, grammarAccess.getXImportDeclarationAccess().getSemicolonKeyword_2());
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_a = new TokenAlias(true, true, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_p = new TokenAlias(true, false, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getArrayBracketsRule())
			return getArrayBracketsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getOpSingleAssignRule())
			return getOpSingleAssignToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * ArrayBrackets :
	 * 	'[' ']'
	 * ;
	 */
	protected String getArrayBracketsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[ ]";
	}
	
	/**
	 * OpSingleAssign:
	 * 	'='
	 * ;
	 */
	protected String getOpSingleAssignToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "=";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_FXControl_CommaKeyword_2_2_q.equals(syntax))
				emit_FXControl_CommaKeyword_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FXControl_CommaKeyword_3_2_q.equals(syntax))
				emit_FXControl_CommaKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FXControl_CommaKeyword_4_2_q.equals(syntax))
				emit_FXControl_CommaKeyword_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FXControl_CommaKeyword_5_2_q.equals(syntax))
				emit_FXControl_CommaKeyword_5_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Field_CommaKeyword_3_2_q.equals(syntax))
				emit_Field_CommaKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Field_CommaKeyword_4_2_q.equals(syntax))
				emit_Field_CommaKeyword_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Field_CommaKeyword_5_2_q.equals(syntax))
				emit_Field_CommaKeyword_5_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Field_CommaKeyword_6_2_q.equals(syntax))
				emit_Field_CommaKeyword_6_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Field_CommaKeyword_7_2_q.equals(syntax))
				emit_Field_CommaKeyword_7_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Metro_CommaKeyword_8_2_0_q.equals(syntax))
				emit_Metro_CommaKeyword_8_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PageContainer_CommaKeyword_3_1_0_q.equals(syntax))
				emit_PageContainer_CommaKeyword_3_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PageContainer_CommaKeyword_4_1_0_q.equals(syntax))
				emit_PageContainer_CommaKeyword_4_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Repository_CommaKeyword_3_2_q.equals(syntax))
				emit_Repository_CommaKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Repository_CommaKeyword_4_2_q.equals(syntax))
				emit_Repository_CommaKeyword_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SQLStatement_CommaKeyword_3_2_q.equals(syntax))
				emit_SQLStatement_CommaKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SQLStatement_CommaKeyword_4_2_q.equals(syntax))
				emit_SQLStatement_CommaKeyword_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SpringMetro_CommaKeyword_7_2_0_q.equals(syntax))
				emit_SpringMetro_CommaKeyword_7_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XBlockExpression_SemicolonKeyword_2_1_q.equals(syntax))
				emit_XBlockExpression_SemicolonKeyword_2_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XExpressionInClosure_SemicolonKeyword_1_1_q.equals(syntax))
				emit_XExpressionInClosure_SemicolonKeyword_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q.equals(syntax))
				emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XImportDeclaration_SemicolonKeyword_2_q.equals(syntax))
				emit_XImportDeclaration_SemicolonKeyword_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XParenthesizedExpression_LeftParenthesisKeyword_0_a.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_XParenthesizedExpression_LeftParenthesisKeyword_0_p.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=EString (ambiguity) ']' (rule end)
	 *     name=EString (ambiguity) 'binding:' binding=Binding
	 *     name=EString (ambiguity) 'columnWidth:' columnWidth=EDouble
	 *     name=EString (ambiguity) 'control:' control=JvmTypeReference
	 *     name=EString (ambiguity) 'description:' description=EString
	 *     name=EString (ambiguity) 'tooltip:' tooltip=EString
	 */
	protected void emit_FXControl_CommaKeyword_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     control=JvmTypeReference (ambiguity) ']' (rule end)
	 *     control=JvmTypeReference (ambiguity) 'binding:' binding=Binding
	 *     control=JvmTypeReference (ambiguity) 'columnWidth:' columnWidth=EDouble
	 *     control=JvmTypeReference (ambiguity) 'description:' description=EString
	 *     control=JvmTypeReference (ambiguity) 'tooltip:' tooltip=EString
	 */
	protected void emit_FXControl_CommaKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     columnWidth=EDouble (ambiguity) ']' (rule end)
	 *     columnWidth=EDouble (ambiguity) 'binding:' binding=Binding
	 *     columnWidth=EDouble (ambiguity) 'description:' description=EString
	 *     columnWidth=EDouble (ambiguity) 'tooltip:' tooltip=EString
	 */
	protected void emit_FXControl_CommaKeyword_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     binding=Binding (ambiguity) ']' (rule end)
	 *     binding=Binding (ambiguity) 'description:' description=EString
	 *     binding=Binding (ambiguity) 'tooltip:' tooltip=EString
	 */
	protected void emit_FXControl_CommaKeyword_5_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=EString (ambiguity) ')' (rule end)
	 *     name=EString (ambiguity) ')' control=FXControl
	 *     name=EString (ambiguity) 'datatype:' datatype=JvmTypeReference
	 *     name=EString (ambiguity) 'isClob:' isClob=EBoolean
	 *     name=EString (ambiguity) 'required:' required=EBoolean
	 *     name=EString (ambiguity) 'useByRepository:' useByRepository=EBoolean
	 *     name=EString (ambiguity) 'useByTableView:' useByTableView=EBoolean
	 */
	protected void emit_Field_CommaKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     datatype=JvmTypeReference (ambiguity) ')' (rule end)
	 *     datatype=JvmTypeReference (ambiguity) ')' control=FXControl
	 *     datatype=JvmTypeReference (ambiguity) 'isClob:' isClob=EBoolean
	 *     datatype=JvmTypeReference (ambiguity) 'required:' required=EBoolean
	 *     datatype=JvmTypeReference (ambiguity) 'useByRepository:' useByRepository=EBoolean
	 *     datatype=JvmTypeReference (ambiguity) 'useByTableView:' useByTableView=EBoolean
	 */
	protected void emit_Field_CommaKeyword_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     isClob=EBoolean (ambiguity) ')' (rule end)
	 *     isClob=EBoolean (ambiguity) ')' control=FXControl
	 *     isClob=EBoolean (ambiguity) 'required:' required=EBoolean
	 *     isClob=EBoolean (ambiguity) 'useByRepository:' useByRepository=EBoolean
	 *     isClob=EBoolean (ambiguity) 'useByTableView:' useByTableView=EBoolean
	 */
	protected void emit_Field_CommaKeyword_5_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     required=EBoolean (ambiguity) ')' (rule end)
	 *     required=EBoolean (ambiguity) ')' control=FXControl
	 *     required=EBoolean (ambiguity) 'useByRepository:' useByRepository=EBoolean
	 *     required=EBoolean (ambiguity) 'useByTableView:' useByTableView=EBoolean
	 */
	protected void emit_Field_CommaKeyword_6_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     useByTableView=EBoolean (ambiguity) ')' (rule end)
	 *     useByTableView=EBoolean (ambiguity) ')' control=FXControl
	 *     useByTableView=EBoolean (ambiguity) 'useByRepository:' useByRepository=EBoolean
	 */
	protected void emit_Field_CommaKeyword_7_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     navigationItems+=[NavigationItem|ID] (ambiguity) navigationItems+=[NavigationItem|ID]
	 */
	protected void emit_Metro_CommaKeyword_8_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     pages+=Page (ambiguity) pages+=Page
	 */
	protected void emit_PageContainer_CommaKeyword_3_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     pages+=FxmlPage (ambiguity) pages+=FxmlPage
	 */
	protected void emit_PageContainer_CommaKeyword_4_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     jdbcUrl=EString (ambiguity) 'generateDummyInsert:' generateDummyInsert=EBoolean
	 *     jdbcUrl=EString (ambiguity) '}' (rule end)
	 *     jdbcUrl=EString (ambiguity) statement+=SQLStatement
	 */
	protected void emit_Repository_CommaKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     generateDummyInsert=EBoolean (ambiguity) '}' (rule end)
	 *     generateDummyInsert=EBoolean (ambiguity) statement+=SQLStatement
	 */
	protected void emit_Repository_CommaKeyword_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=EString (ambiguity) ')' (rule end)
	 *     name=EString (ambiguity) 'query:' query=EString
	 *     name=EString (ambiguity) 'returnValue:' returnValue=JvmTypeReference
	 */
	protected void emit_SQLStatement_CommaKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     query=EString (ambiguity) ')' (rule end)
	 *     query=EString (ambiguity) 'returnValue:' returnValue=JvmTypeReference
	 */
	protected void emit_SQLStatement_CommaKeyword_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     elements+=[NavigationItem|ID] (ambiguity) elements+=[NavigationItem|ID]
	 */
	protected void emit_SpringMetro_CommaKeyword_7_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) '}' ')' (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) '}' (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) expressions+=XExpressionOrVarDeclaration
	 */
	protected void emit_XBlockExpression_SemicolonKeyword_2_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) expressions+=XExpressionOrVarDeclaration
	 */
	protected void emit_XExpressionInClosure_SemicolonKeyword_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '=>' returnType=JvmTypeReference
	 */
	protected void emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     importedNamespace=QualifiedNameWithWildcard (ambiguity) (rule end)
	 *     importedType=[JvmDeclaredType|QualifiedName] (ambiguity) (rule end)
	 *     memberName=ValidID (ambiguity) (rule end)
	 *     wildcard?='*' (ambiguity) (rule end)
	 */
	protected void emit_XImportDeclaration_SemicolonKeyword_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '#' '[' ']' (rule start)
	 *     (rule start) (ambiguity) '#' '[' elements+=XExpression
	 *     (rule start) (ambiguity) '#' '{' '}' (rule start)
	 *     (rule start) (ambiguity) '#' '{' elements+=XExpression
	 *     (rule start) (ambiguity) '<' typeArguments+=JvmArgumentTypeReference
	 *     (rule start) (ambiguity) '[' declaredFormalParameters+=JvmFormalParameter
	 *     (rule start) (ambiguity) '[' explicitSyntax?='|'
	 *     (rule start) (ambiguity) '[' expression=XExpressionInClosure
	 *     (rule start) (ambiguity) 'do' body=XExpression
	 *     (rule start) (ambiguity) 'false' (rule start)
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' ')' eachExpression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' updateExpressions+=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' expression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'for' '(' initExpressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) 'if' '(' if=XExpression
	 *     (rule start) (ambiguity) 'new' constructor=[JvmConstructor|QualifiedName]
	 *     (rule start) (ambiguity) 'null' (rule start)
	 *     (rule start) (ambiguity) 'return' (rule start)
	 *     (rule start) (ambiguity) 'return' expression=XExpression
	 *     (rule start) (ambiguity) 'switch' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' switch=XExpression
	 *     (rule start) (ambiguity) 'synchronized' '(' param=XExpression
	 *     (rule start) (ambiguity) 'throw' expression=XExpression
	 *     (rule start) (ambiguity) 'try' expression=XExpression
	 *     (rule start) (ambiguity) 'typeof' '(' type=[JvmType|QualifiedName]
	 *     (rule start) (ambiguity) 'while' '(' predicate=XExpression
	 *     (rule start) (ambiguity) '{' '}' (rule start)
	 *     (rule start) (ambiguity) '{' expressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|FeatureCallID]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|IdOrSuper]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|OpUnary]
	 *     (rule start) (ambiguity) isTrue?='true'
	 *     (rule start) (ambiguity) value=Number
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {XAssignment.assignable=}
	 *     (rule start) (ambiguity) {XBinaryOperation.leftOperand=}
	 *     (rule start) (ambiguity) {XCastedExpression.target=}
	 *     (rule start) (ambiguity) {XInstanceOfExpression.expression=}
	 *     (rule start) (ambiguity) {XMemberFeatureCall.memberCallTarget=}
	 *     (rule start) (ambiguity) {XPostfixOperation.operand=}
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '#' '[' ']' ')' (rule start)
	 *     (rule start) (ambiguity) '#' '[' elements+=XExpression
	 *     (rule start) (ambiguity) '#' '{' '}' ')' (rule start)
	 *     (rule start) (ambiguity) '#' '{' elements+=XExpression
	 *     (rule start) (ambiguity) '<' typeArguments+=JvmArgumentTypeReference
	 *     (rule start) (ambiguity) '[' declaredFormalParameters+=JvmFormalParameter
	 *     (rule start) (ambiguity) '[' explicitSyntax?='|'
	 *     (rule start) (ambiguity) '[' expression=XExpressionInClosure
	 *     (rule start) (ambiguity) 'do' body=XExpression
	 *     (rule start) (ambiguity) 'false' ')' (rule start)
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' ')' eachExpression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' updateExpressions+=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' expression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'for' '(' initExpressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) 'if' '(' if=XExpression
	 *     (rule start) (ambiguity) 'new' constructor=[JvmConstructor|QualifiedName]
	 *     (rule start) (ambiguity) 'null' ')' (rule start)
	 *     (rule start) (ambiguity) 'return' ')' (rule start)
	 *     (rule start) (ambiguity) 'return' expression=XExpression
	 *     (rule start) (ambiguity) 'switch' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' switch=XExpression
	 *     (rule start) (ambiguity) 'synchronized' '(' param=XExpression
	 *     (rule start) (ambiguity) 'throw' expression=XExpression
	 *     (rule start) (ambiguity) 'try' expression=XExpression
	 *     (rule start) (ambiguity) 'typeof' '(' type=[JvmType|QualifiedName]
	 *     (rule start) (ambiguity) 'while' '(' predicate=XExpression
	 *     (rule start) (ambiguity) '{' '}' ')' (rule start)
	 *     (rule start) (ambiguity) '{' expressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|FeatureCallID]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|IdOrSuper]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|OpUnary]
	 *     (rule start) (ambiguity) isTrue?='true'
	 *     (rule start) (ambiguity) value=Number
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {XAssignment.assignable=}
	 *     (rule start) (ambiguity) {XBinaryOperation.leftOperand=}
	 *     (rule start) (ambiguity) {XCastedExpression.target=}
	 *     (rule start) (ambiguity) {XInstanceOfExpression.expression=}
	 *     (rule start) (ambiguity) {XMemberFeatureCall.memberCallTarget=}
	 *     (rule start) (ambiguity) {XPostfixOperation.operand=}
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
