/*
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractEntityDslScopeProvider extends XbaseBatchScopeProvider {
}
