/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang;

import de.dc.entity.lang.AbstractEntityDslRuntimeModule;
import de.dc.entity.lang.generator.EntityDslGenerator;
import org.eclipse.xtext.generator.IGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntityDslRuntimeModule extends AbstractEntityDslRuntimeModule {
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return EntityDslGenerator.class;
  }
}
