/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang;

import de.dc.entity.lang.EntityDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntityDslStandaloneSetup extends EntityDslStandaloneSetupGenerated {
  public static void doSetup() {
    new EntityDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
