/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.validation;

import de.dc.entity.lang.validation.AbstractEntityDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EntityDslValidator extends AbstractEntityDslValidator {
}
