/**
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang.ui;

import de.dc.entity.lang.ui.AbstractEntityDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EntityDslUiModule extends AbstractEntityDslUiModule {
  public EntityDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
