/*
 * generated by Xtext 2.17.0
 */
package de.dc.entity.lang

import de.dc.entity.lang.generator.EntityDslGenerator

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EntityDslRuntimeModule extends AbstractEntityDslRuntimeModule {
	
	override bindIGenerator() {
		EntityDslGenerator
	}
	
}
